# .github/workflows/custom-deploy.yml
on:
  push:
    branches: ['test']

jobs:
  custom-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_SECRET
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_SECRET
          EOF
        env:
          HEROKU_SECRET: ${{ secrets.HEROKU_SECRET }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add Heroku remote
        run: heroku git:remote -a $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: Remote repository
        run: git remote -v
      - name: Add
        run: git add .
      - name: Commit
        run: |
          git config --global user.email "Vivekhande16sep@gmail.com"
          git config --global user.name "VivekHande16"
          git commit -m "Added all files"
      - name: Push to Heroku
        run: git push heroku master
