# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information  see: https ://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ['feature-reviews']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.Heroku_secret }}
          heroku_app_name: 'vanity-swiggy-for-salons-be'
          heroku_email: 'axcal16@gmail.com'
